In [1]:
#aq araferi shecvalo darune ubralod

georgian_to_english = {
    "ა": "a",
    "ბ": "b",
    "გ": "g",
    "დ": "d",
    "ე": "e",
    "ვ": "v",
    "ზ": "z",
    "თ": "T",
    "ი": "i",
    "კ": "k",
    "ლ": "l",
    "მ": "m",
    "ნ": "n",
    "ო": "o",
    "პ": "p",
    "ჟ": "J",
    "რ": "r",
    "ს": "s",
    "ტ": "t",
    "უ": "u",
    "ფ": "f",
    "ქ": "q",
    "ღ": "R",
    "ყ": "y",
    "შ": "S",
    "ჩ": "C",
    "ც": "c",
    "ძ": "Z",
    "წ": "w",
    "ჭ": "W",
    "ხ": "x",
    "ჯ": "j",
    "ჰ": "h",
}


english_to_georgian = {
    "a": "ა",
    "S": "შ",
    "C": "ჩ",
    "R": "ღ",
    "Z": "ძ",
    "b": "ბ",
    "g": "გ",
    "d": "დ",
    "q":"ქ",
    "e": "ე",
    "v": "ვ",
    "z": "ზ",
    "T": "თ",
    "t":"ტ",
    "i": "ი",
    "k": "კ",
    "l": "ლ",
    "m": "მ",
    "n": "ნ",
    "o": "ო",
    "p": "პ",
    "r": "რ",
    "s": "ს",
    "u": "უ",
    "f": "ფ",
    "y": "ყ",
    "c": "ც",
    "w": "წ",
    "x": "ხ",
    "W": "ჭ",
    "j": "ჯ",
    "h": "ჰ",
}

def targmna(text, to="ka"):
    
    nacarqeqia_replaced = text.replace('მთავარი გმირი:', 'ნაცარქექია: ')
    naCarqeqia_replaced = text.replace('naCarqeqia','nacarqeqia')

    if to == "eng":
        for letter in georgian_to_english:
            nacarqeqia_replaced = nacarqeqia_replaced.replace(letter, georgian_to_english[letter])
    else: 
        for letter in english_to_georgian:
            nacarqeqia_replaced = nacarqeqia_replaced.replace(letter, english_to_georgian[letter])
    # print(nacarqeqia_replaced)
    lines = nacarqeqia_replaced.splitlines()

    # Iterate through the lines
    for line in lines:
        print(line)

# amis qveda blokshi chasvi teqsti

In [3]:
text = '''
ნაცარქექია: მარტო რას აკეთებ ტყეში, დახმარება ხომ არ გინდა?
უცნობი ბავშვი: დიახ,  მე უბრალოდ ვემალები სხვა ბავშვებს. ყოველთვის დამცინიან და ცუდ სიტყვებს მეძახიან.
ნაცარქექია: მე სკოლა დიდი ხნის დამთავრებული მაქვს, მეც ბევრი რამ შემემთხვა, მომიყევი რა გგჭირვებია, იქნებ დახმარება შევძლო.

უცნობი ბავშვი: ჩვენ, სოკოებს მასწავლებლები და ბავშვები ზედაც არ გვიყურებენ. თავს გარიყულად და დასჯილად ვგრძნობ.
ნაცარქექია: მიამბე აბა რა დაგმართნია და გეტყვი როგორ უნდა მოიქცე.~ პირველი
უცნობი ბავშვი: დღეს სკოლაში რომ მივედი ჩემი კლასელი კუთხეში იჯდა და ტიროდა. სხვა ბავშვებმა დაუწყეს დაცინვა და სათამაშოებს ესროდნენ. მას ყველა დასცინოდა მე კი არ ვიცოდი რა მეღონა. შენ რას გააკეთებდი ჩემს მაგივრად?

- შევუერთდებოდი დანარჩენებს და ერთად დავცინებდით
	ნაცარქექია: დაცინვა არ შეიძლება, კარგი ბავშვები კი ასე არ იქცევიან. თავიდან სცადე...
	=> პირველი

- ყურადღებას არ მივაქცევდი
	ნაცარქექია: ადამიანს არ უნდა დასცინო, ვისაც დასცინიან, უნდა დაეხმარო! თავიდან სცადე...
	=> პირველი
- ხმამაღლა მოვთხოვდი რომ შეწყვიტონ დაცინვა და ჩემ კლასელს გავიყვანდი უსაფრთხო ადგილას, დავამშვიდებდი, შემდეგ კი ვეტყოდი უფროსებს.
	ნაცარქექია: ყოჩაღ, სწორი პასუხია! დაცინვა  ცუდი საქციელია.

- ვიდეო გადაიღო და დანარჩენებს აჩვენო, სხვებმაც რომ დასცინონ
	ნაცარქექია: არა, ასე არ უნდა მოიქცე. ადამიანის დაცინვა ცუდი საქციელია. თავიდან სცადე..
=> პირველი.

უცნობი ბავშვი: მადლობა, შემდეგში აუცილებლად ეგრე მოვიქცევი! გავაგრძელებ მოყოლას

~ მეორე
უცნობი ბავშვი: შემდგომ, დასვენებაზე ჩემს მეგობარ ყვითელქუდა სოკოს უცნობი ადამიანი ყვითელი ქუდის გამო დამცინავ წერილებს უგზავნდა, ჩემი მეგობარი კი დამწუხრებულია, რა უნდა მოვიმოქმედო შემდეგში პრობლემის გადასაჭრელად??
- შევუერთდე მჩაგვრელს და დავცინო
	ნაცარქექია: ადამიანის დაცინვა ძალიან ცუდი საქციელია. ეს პასუხი არ არის სწორი, თავიდან სცადე...
	=> მეორე
- ვაცნობო ფოსტას, რომ მჩაგვრელისგან აღარ მიიღოს წერილები და დავამშვიდო ჩემი მეგობარი
	ნაცარქექია: ეს სწორი პასუხია! დაზარალებულის დაცვა ყოველთვის უნდა ეცადო.
- ყურადღება არ მიაქციო,, რადგან ეს შენი პრობლემა არ არის
	ნაცარქექია: ეს არასწორი პასუხია, ხმა მაშინ უნდა ამოიღო, როდესაც ხედავ, რომ ადამიანს ჩაგრავენ. თავიდან სცადე...
	=> მეორე


	
~ მესამე
უცნობი ბავშვი:  დღეს კი ჩემი მეგობარი დასცინოდა მისგან განსხვავებულ კლასელებს, იმიტომ, რომ ზოგს მსხვილი ღერო აქვს, ზოგს ბევრი კოპლები, ზოგს კი ფერადი ქუდები,არ ვიცოდი რა მეღონა რომ გამეჩერებინა. 
- შენც შეუერთდე და ერთად დასცინოთ
	ნაცარქექია: ასე არ უნდა მოიქცე, ცუდი საქციელია დაცინვა. თავიდან სცადე...
	=> მესამე
- ყურდღება არ მიაქციო და გაიარო
	ნაცარქექია: ვისაც დასცინიან უნდა დაეხმარო . თავიდან სცადე...
	=> მესამე

- უთხრა შენს მეგობარს, რომ ღეროს, კოპლებსა და ქუდებს მნიშვნელობა არ აქვს, ყველანი ერთნაირები ვართ და მათი ჩვენგან გამოყოფა გულს ტკენს ყველას. 
	ნაცარქექია: ეს სწორი პასუხია! ადამიანის დამცირება იმის გამო, რომ შენგან განსხვავებულია, დაუშვებელია!
	


უცნობი ბავშვი: ბოლო გაკვეთილზეც დავიბენი, რადგან არ ვიცოდი როგორ მოვქცეულიყავი.
~ მეოთხე
უცნობი ბავშვი: ჩემი ისტორიის მასწავლებელი სოკოებს უკანა მერხებზე გვსვამს, წინ დასხდომა არ შეგვიძლია და ყოველთვის გვეუბნება, რომ სოკოები დამნაშავეები არიან. ეს ნორმალურია? ამ დროს როგორ მოვიქცე ხოლმე?
- უთხრა ეს ამბავი დამრიგებელს / დირექტორს რათა მიიღონ შესაბამისი ზომები
	ნაცარქექია: პასუხი სწორია!
- დაემორჩილო მას, რადგან მასწავლებელი ყოველთვის მართალია
	ნაცარქექია: არავინაა ყოველთვის მართალი, არასდროს შეიზღუდო თავი და დასვი კითხვა- რატომ? პასუხი არასწორია, თავიდან სცადე...
	=> მეოთხე
- არ მიაქციო ყურადღება
	ნაცარქექია: პასუხი არასწორია, თავიდან სცადე...
	=> მეოთხე
	
ნაცარქექია: ყოჩაღ! შენ უკვე შეგიძლია გაარჩიო რა არის ცუდი და რა კარგი საქციელი! 
ნაცარქექია: კარგად. მომავალ შეხვედრამდე!
=> ენდ
 


'''


# gaushvi qveda bloki
## tu ginda ro inglisuridan qartulze targmnos "eng" is nacvlad chawere ka

In [4]:
targmna(text, "eng")


nacarqeqia: marto ras akeTeb tyeSi, daxmareba xom ar ginda?
ucnobi bavSvi: diax,  me ubralod vemalebi sxva bavSvebs. yovelTvis damcinian da cud sityvebs meZaxian.
nacarqeqia: me skola didi xnis damTavrebuli maqvs, mec bevri ram SememTxva, momiyevi ra ggWirvebia, iqneb daxmareba SevZlo.

ucnobi bavSvi: Cven, sokoebs maswavleblebi da bavSvebi zedac ar gviyureben. Tavs gariyulad da dasjilad vgrZnob.
nacarqeqia: miambe aba ra dagmarTnia da getyvi rogor unda moiqce.~ pirveli
ucnobi bavSvi: dRes skolaSi rom mivedi Cemi klaseli kuTxeSi ijda da tiroda. sxva bavSvebma dauwyes dacinva da saTamaSoebs esrodnen. mas yvela dascinoda me ki ar vicodi ra meRona. Sen ras gaakeTebdi Cems magivrad?

- SevuerTdebodi danarCenebs da erTad davcinebdiT
	nacarqeqia: dacinva ar SeiZleba, kargi bavSvebi ki ase ar iqcevian. Tavidan scade...
	=> pirveli

- yuradRebas ar mivaqcevdi
	nacarqeqia: adamians ar unda dascino, visac dascinian, unda daexmaro! Tavidan scade...
	=> pirveli
- xmamaRla movTxovdi rom Sewyviton 

In [2]:
string = '''
ტბის ფერია: gamarjoba nacarqeqia.
ნაცარქექია: gamarjoba.
ტბის ფერია: mipasuxe kiTxvebze sworad da jadosnuri gragniliT dagajildoveb.
ნაცარქექია: mzad var.
ტბის ფერია: pirveli SekiTxva:
~ pirveli
ტბის ფერია: nacarqeqia, molaparake Citisgan iReb idumal gzavnils, romelic gawvdis siaxleebsa da mosazrebebs msoflios Sesaxeb. rogor gaigeb aris Tu ara es Citi sando?   
- Seafaseb mis mier mowodebul mtkicebulebebs da daadastureb sxva wayraoebidan. 
	ტბის ფერია: pasuxi sworia! 
- endobi molaparake Cits, radgan molaparake Citis sityvebs sibrZne unda hqondes.
	ტბის ფერია: samwuxarod pasuxi arasworia! 
	Cven ar unda vivaraudoT, rom vinme aris mcodne an sando, maTi SesaZleblobebis safuZvelze da ara realuri mtkicebulebebiT. xolo molaparake frinvelebi sulac ar aris informaciis sando wyaro.
	axla ki Tavidan mipasuxe kiTxvaze.
	=> pirveli
- ugulebelyob Citis Setyobinebas gadamowmebis gareSe. 
	ტბის ფერია: samwuxarod pasuxi arasworia!
	pasuxi uaryofs molaparake frinvelis gzavnilis kritikuli Sefasebis gareSe. mniSvnelovania maTi pretenziis Sefaseba Sinaarsisa da konteqstidan gamomdinare, araTu varaudebis gakeTeba.
	axla ki Tavidan mipasuxe kiTxvaze.
	=> pirveli
	
ტბის ფერია: meore SekiTxva:
~ meore
ტბის ფერია: nacarqeqia, Sen waawyedebi arsebas, romelic formas icvlis sxvebis mosatyueblad. rogor gamoicnob mis realur bunebas?
- endobi Sens grZnobebs da daeTanxmebi nebismier formas, romelsac arseba miiRebs.
	ტბის ფერია: pasuxi arasworia!
	formis cvladi arseba SeiZleba iyos matyuara da maTi garegnoba yovelTvis sando araa. mxolod grZnobebze dayrdnobiT msjelobam SeiZleba SecdomaSi SegiyvanoT.
	scade xelaxla.
	=> meore
- daakvirdebi mis qcevas da qmedebebs, ramac SeiZleba gamoavlinos misi realuri saxe.
	ტბის ფერია: pasuxi sworia!
- SegeSindeba am arsebis, radgan es unari mas saxifaTos xdis.
	ტბის ფერია: pasuxi arasworia!
	arsebis Tavidan acileba ar dagexmarebaT misi realuri saxis gamovlenaSi. aman SeiZleba xeli SeuSalos Rirebuli informaciis aRmoCenas, an Tundac mixvdes rom arseba saSiSi sulac araa.
	scade xelaxla
	=> meore
ტბის ფერია: mesame SekiTxva:
~ mesame
ტბის ფერია: nacarqeqia, aRmoCndi molaparake xeebis tyeSi, sadac TiToeuli saidumloebs CurCulebs da istoriebs aziarebs. rogor gaarkvev romelia zRapari da romeli ubralod qaris CurCuli?
- daijerebs yvelafers, radgan xeebi brZeni da uZvelesi arsebebi arian.
	ტბის ფერია: pasuxi arasworia!
	brZeni arsebebis ki SeiZleba Secdne, mikerZoebulebi an sakuTari gavlenis qveS imyofebodnen. yvelaferi ar unda daijero rasac isini amboben.
	scade xelaxla.
	=> mesame
- Seafaseb istoriebis Tanmimdevrobasa da konteqsts, daadastureb sxva wyaroebidanac.
	ტბის ფერია: pasuxi sworia!
- daaignoreb xeebis CurCuls da koncentrirdebi sakuTar gzaze.
	ტბის ფერია: pasuxi arasworia!
	xeebis sruliad uaryofam SeiZleba wagarTvas potenciurad Rirebuli informacia. maSinac ki Tu zogierTi CurCuli mcdaria, maT SeiZleba hqondeT simarTlis niSnebi.
	scade xelaxla.
	=> mesame
ტბის ფერია: es codna da gragnili momavalSi aucileblad dagexmareba.

'''
lines = string.splitlines()


for line in lines:
    print(line)


ტბის ფერია: gamarjoba nacarqeqia.
ნაცარქექია: gamarjoba.
ტბის ფერია: mipasuxe kiTxvebze sworad da jadosnuri gragniliT dagajildoveb.
ნაცარქექია: mzad var.
ტბის ფერია: pirveli SekiTxva:
~ pirveli
ტბის ფერია: nacarqeqia, molaparake Citisgan iReb idumal gzavnils, romelic gawvdis siaxleebsa da mosazrebebs msoflios Sesaxeb. rogor gaigeb aris Tu ara es Citi sando?   
- Seafaseb mis mier mowodebul mtkicebulebebs da daadastureb sxva wayraoebidan. 
	ტბის ფერია: pasuxi sworia! 
- endobi molaparake Cits, radgan molaparake Citis sityvebs sibrZne unda hqondes.
	ტბის ფერია: samwuxarod pasuxi arasworia! 
	Cven ar unda vivaraudoT, rom vinme aris mcodne an sando, maTi SesaZleblobebis safuZvelze da ara realuri mtkicebulebebiT. xolo molaparake frinvelebi sulac ar aris informaciis sando wyaro.
	axla ki Tavidan mipasuxe kiTxvaze.
	=> pirveli
- ugulebelyob Citis Setyobinebas gadamowmebis gareSe. 
	ტბის ფერია: samwuxarod pasuxi arasworia!
	pasuxi uaryofs molaparake frinvelis gzavnilis kritikuli Sefasebis gar

{'ა': 'a',
 'ბ': 'b',
 'გ': 'g',
 'დ': 'd',
 'ე': 'e',
 'ვ': 'v',
 'ზ': 'z',
 'თ': 'T',
 'ი': 'i',
 'კ': 'k',
 'ლ': 'l',
 'მ': 'm',
 'ნ': 'n',
 'ო': 'o',
 'პ': 'p',
 'ჟ': 'J',
 'რ': 'r',
 'ს': 's',
 'ტ': 't',
 'უ': 'u',
 'ფ': 'f',
 'ქ': 'q',
 'ღ': 'R',
 'ყ': 'y',
 'შ': 'S',
 'ჩ': 'C',
 'ც': 'C',
 'ძ': 'Z',
 'წ': 'w',
 'ჭ': 'W',
 'ხ': 'x',
 'ჯ': 'j',
 'ჰ': 'h'}

In [3]:
import numpy as np

A = np.array([[56.0,0.0,4.4,68.0],
              [1.2,104.0,52.0,8.0],
              [1.8,135.0,99.0,0.9]])

In [4]:
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [53]:
cal = A.sum(0)
print(cal)

[ 59.  239.  155.4  76.9]


In [67]:
perc = A/cal

In [68]:
perc

array([[0.94915254, 0.        , 0.02831403, 0.88426528],
       [0.02033898, 0.43514644, 0.33462033, 0.10403121],
       [0.03050847, 0.56485356, 0.63706564, 0.01170351]])